description: Investigation numérique, développement web et ethical hacking
title: Gauthier Montavon  
logo: photo.jpg
# Use a relative path to logo image 
# description: Geek Rider
# show_downloads: true # Fix spelling
theme: jekyll-theme-minimal 
#plugins:
#  - jekyll-seo-tag
email: gauthier.montavon@gmail.com
